---
controller_settings:
  - settings:
      INSTALL_UUID: "b89b00ff-84ea-4d34-a768-823c215a8f26"
      AWX_TASK_ENV:
        GIT_SSL_NO_VERIFY: 'True'
        HOME: /var/lib/awx
      CUSTOM_LOGIN_INFO: "Configuration as Code Migration Test"
      AUTH_LDAP_SERVER_URI: ""
      AUTH_LDAP_BIND_DN: ""
      AUTH_LDAP_BIND_PASSWORD: ""
      AUTH_LDAP_START_TLS: "false"
      AUTH_LDAP_USER_SEARCH:
        []
      AUTH_LDAP_USER_DN_TEMPLATE: "null"
      AUTH_LDAP_USER_ATTR_MAP:
        {}
      AUTH_LDAP_GROUP_SEARCH:
        []
      AUTH_LDAP_GROUP_TYPE: "MemberDNGroupType"
      AUTH_LDAP_GROUP_TYPE_PARAMS:
        member_attr: member
        name_attr: cn
      AUTH_LDAP_REQUIRE_GROUP: "null"
      AUTH_LDAP_DENY_GROUP: "null"
      AUTH_LDAP_USER_FLAGS_BY_GROUP:
        {}
      AUTH_LDAP_ORGANIZATION_MAP:
        {}
      AUTH_LDAP_TEAM_MAP:
        {}
...
