---
controller_credentials:
  - name: "Automation Hub Container Registry"
    description: ""
    credential_type: "Container Registry"
    organization: "Recursive Workflows"
    inputs:
      host: automation.hub
      password: ''
      username: admin
      verify_ssl: true

...
