---
controller_credentials:
  - name: "TOWER-HUB-Cluster-Kubeconfig"
    description: ""
    credential_type: "Kubeconfig"
    organization: "TOWER-ORG"
    inputs:
      kube_config: "{{ vault_hub_kubeconfig_file_content }}" 
...
