---
controller_inventory_sources:
  - name: "awx-org Inventory Source"
    description: ""
    organization: "awx-org"
    source: "scm"
    source_project: "awx-org Project"
    source_path: "{{ inventory_source_path }}"
    inventory: "awx-org Inventory"
    update_on_launch: "False"
    overwrite: "True"
    credential: "HUB Cluster Kubeconfig"
    execution_environment: "ee-awx-org"
...
