---
controller_inventory_sources:
  - name: "Auto-created source for: All Managed Clusters Not Done"
    organization: "awx-org"
    inventory: "All Managed Clusters Not Done"
    source_vars:
      plugin: constructed
    limit: "all-managed-clusters-not-done"
...
