---
controller_credentials:
  - name: "TOWER-Git-Credential"
    description: ""
    credential_type: "Source Control"
    organization: "TOWER-ORG"
    inputs:
      ssh_key_data: "{{ vault_git_ssh_key_data }}"
      username: tower-git-cred-temp

...
