---
controller_credentials:
  - name: "TOWER-Machine Credential"
    description: ""
    credential_type: "Machine"
    organization: "TOWER-ORG"
    inputs:
      password: "{{ vault_user_aap_pwd }}"
      username: admin
...
