---
controller_inventories:
  - name: "All Managed Clusters Done"
    description: ""
    organization: "awx-org"
    kind: "constructed"
    input_inventories:
    - "awx-org Inventory"
    variables:
      ansible_python_interpreter: /usr/bin/python3.9
...
