---
controller_user_accounts:
- username: "admin"
  password: "{{ controller_password }}"
  email: "root@localhost"
  first_name: ""
  last_name: ""
  auditor: "False"
  superuser: "True"
  update_secrets: False
...
