---
controller_user_accounts:
- username: "awx-org-user"
  password: "{{ vault_user_aap_pwd }}"
  email: "awx-org-user@email.com"
  first_name: "AWX"
  last_name: "USER"
  auditor: "False"
  superuser: "False"
  update_secrets: False
...
