---
controller_templates:
  - name: "Managed Clusters Day2 Automation"
    description: ""
    organization: "awx-org"
    project: "awx-org Project"
    inventory: "All Managed Clusters Not Done"
    playbook: "{{ playbook_source_path }}"
    job_type: "run"
    fact_caching_enabled: "False"
    credentials:
      - "HUB Cluster Kubeconfig"
    concurrent_jobs_enabled: "False"
    ask_scm_branch_on_launch: "False"
    ask_tags_on_launch: "False"
    ask_verbosity_on_launch: "False"
    ask_variables_on_launch: "False"
    extra_vars:
      namespace_to_add: acm-day2-automation-with-aap
      state: present
    execution_environment: "ee-awx-org"
    survey_enabled: False
    survey_spec: {}
...
