---
controller_workflows:
  - name: "Inventory Sync"
    description: ""
    organization: "awx-org"
    state: "present"
    simplified_workflow_nodes:
      - identifier: "Project_Sync"
        workflow_job_template: "Inventory Sync"
        unified_job_template: "awx-org Project"
        organization: "awx-org"
        all_parents_must_converge: "False"
        success_nodes:
          - INVENTORY_SYNC
      - identifier: "INVENTORY_SYNC"
        workflow_job_template: "Inventory Sync"
        unified_job_template: "awx-org Inventory Source"
        organization: "awx-org"
        all_parents_must_converge: "False"
        success_nodes:
          - CONSTR_INV_SYNC_ALL_MANAGED
          - CONSTR_INV_SYNC_ALL_MANAGED_DONE
          - CONSTR_INV_SYNC_ALL_MANAGED_NOT_DONE
      - identifier: "CONSTR_INV_SYNC_ALL_MANAGED"
        workflow_job_template: "Inventory Sync"
        unified_job_template: "Auto-created source for: All Managed Clusters"
        organization: "awx-org"
        all_parents_must_converge: "False"
      - identifier: "CONSTR_INV_SYNC_ALL_MANAGED_DONE"
        workflow_job_template: "Inventory Sync"
        unified_job_template: "Auto-created source for: All Managed Clusters Done"
        organization: "awx-org"
        all_parents_must_converge: "False"
      - identifier: "CONSTR_INV_SYNC_ALL_MANAGED_NOT_DONE"
        workflow_job_template: "Inventory Sync"
        unified_job_template: "Auto-created source for: All Managed Clusters Not Done"
        organization: "awx-org"
        all_parents_must_converge: "False"
    survey_enabled: "False"
    ask_variables_on_launch: "False"
    allow_simultaneous: "False"
    scm_branch: ""
    webhook_service: ""
    survey_enabled: False
    survey_spec: {}
...
