---
controller_credentials:
  - name: "AWX-Machine Credential"
    description: ""
    credential_type: "Machine"
    organization: "AWX-ORG"
    inputs:
      password: "{{ controller_password }}"
      username: admin

...
