---
controller_credentials:
  - name: "Git Credential"
    description: ""
    credential_type: "Source Control"
    organization: "awx-org"
    inputs:
      username: "{{ git_user }}"
      ssh_key_data: "{{ git_ssh_key_data }}"
...
