---
# controller_credentials:
#   - name: "awx-org Disconnected Registry"
#     description: ""
#     credential_type: "Container Registry"
#     organization: "awx-org"
#     inputs:
#       host: "{{ disconnected_registry_host }}"
#       password: "{{ disconnected_registry_pwd }}"
#       username: "{{ disconnected_registry_user }}"
#       verify_ssl: false
#
...
