---
# controller_instance_groups:
#   - name: "controlplane"
#     policy_instance_minimum: "0"
#     policy_instance_percentage: "100"
#     instances:
#       - "control-plane.instance.1"
#   - name: "default"
#     policy_instance_minimum: "0"
#     policy_instance_percentage: "100"
#     instances:
#       - "default.instance.1"
...
